QFGreenBean/QFGreenBean/Controllers/ConstraintController.cs
using QFGreenBean.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Core;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QFGreenBean.Controllers
{
    public class ConstraintController : Controller
    {
        private PlannerDbEntities listDB = new PlannerDbEntities();
        // GET: Constraint
        public ActionResult Index()
        {
            return View();
        }


        // GET: Constraint
        public ActionResult Add()
        {
            return View();
        }

        // POST: Constraint/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitConstraint([Bind(Include = "Day,StartHour,EndHour,StartMinute,EndMinute")] StudentConstraint constraint)
        {

            int start = Convert.ToInt32(constraint.StartHour + constraint.StartMinute);
            int end = Convert.ToInt32(constraint.EndHour + constraint.EndMinute);
            if (end <= start)
            {
                ModelState.AddModelError("EndHour", "End hour must be later than start");
            }

            if (ModelState.IsValid)
            {
                listDB.StudentConstraints.Add(constraint);
                listDB.SaveChanges();
            }

            return RedirectToAction("ViewConstraints");
        }

        // POST: Constraint/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConstraint(int StudentConstraintId)
        {
            StudentConstraint c = listDB.StudentConstraints.Find(StudentConstraintId);
            listDB.StudentConstraints.Remove(c);
            listDB.SaveChanges();

            return RedirectToAction("ViewConstraints");
        }

        public string TestConstraint(StudentConstraint c)
        {
            string s = "Value of WeekDay is: " + c.Day.ToLower() + "\n";
            s += "startHour: " + c.StartHour + "\n";
            s += "startMinute: " + c.StartMinute + "\n";
            s += "endHour: " + c.EndHour + "\n";
            s += "endMinute: " + c.EndMinute + "\n";
            return s;
        }

        // GET: Constraint
        public ActionResult ViewConstraints()
        {
            return View(listDB.StudentConstraints.ToList());
        }

    }
}

QFGreenBean/QFGreenBean/Views/Constraint/ViewConstraints.cshtml
@model List<QFGreenBean.Models.StudentConstraint>

@{
    ViewBag.Title = "View Constraints";
}

<style type="text/css">
    footer {
        clear: both;
    }

    table#list {
        float: right;
    }

    .tg {
        float: left;
        border-collapse: collapse;
        border-spacing: 0;
        border-color: #aabcfe;
    }

        .tg td {
            font-family: Arial, sans-serif;
            font-size: 14px;
            padding: 10px 20px;
            border-style: solid;
            border-width: 1px;
            overflow: hidden;
            word-break: normal;
            border-color: #aabcfe;
            color: #669;
            background-color: #e8edff;
            text-align: center;
        }

        .tg th {
            font-family: Arial, sans-serif;
            font-size: 14px;
            font-weight: normal;
            padding: 10px 20px;
            border-style: solid;
            border-width: 1px;
            overflow: hidden;
            word-break: normal;
            border-color: #aabcfe;
            color: #039;
            background-color: #b9c9fe;
            text-align: center;
        }

        .tg .tg-yw4l {
            vertical-align: top;
        }

        .tg .blocked {
            background: rgba(210, 44, 44, 0.9);
        }
</style>

@{
    List<string> hourItems = new List<string>();
    for (int i = 8; i <= 22; i++)
    {
        hourItems.Add(Convert.ToString(i));
    }

    List<string> minuteItems = new List<string>();
    minuteItems.Add("00");
    minuteItems.Add("15");
    minuteItems.Add("30");
    minuteItems.Add("45");

    List<string> columns = new List<string>();
    columns.Add("HOUR");
    columns.Add("Monday");
    columns.Add("Tuesday");
    columns.Add("Wednesday");
    columns.Add("Thursday");
    columns.Add("Friday");
}

@functions {
    public bool isConstrained(string day, string hour, string minute)
    {
        System.Diagnostics.Debug.WriteLine("Params:" + day + " " + hour + " " + minute);
        List<QFGreenBean.Models.StudentConstraint> cList = Model;
        foreach (QFGreenBean.Models.StudentConstraint constraint in cList)
        {
            System.Diagnostics.Debug.WriteLine("Constraint: " + constraint);
            //Start
            if (constraint.Day == day && constraint.StartHour == hour && constraint.StartMinute == minute)
                return true;
            //End
            if (constraint.Day == day && constraint.EndHour == hour && constraint.EndMinute == minute)
                return true;
            //In Between
            int start = Convert.ToInt32(constraint.StartHour + constraint.StartMinute);
            int end = Convert.ToInt32(constraint.EndHour + constraint.EndMinute);
            int param = Convert.ToInt32(hour + minute);
            System.Diagnostics.Debug.WriteLine("Ints are: start[" + start + "], end[" + end + "], param[" + param + "]");
            if ((param >= start) && (param <= end) && (constraint.Day == day.ToLower()))
                return true;

        }

        return false;
    }
}

<h2>View Constraints</h2>

<table class="tg">
    <tr>
        @foreach (var col in columns)
        {
            if (col == "HOUR")
            {
                <th class="tg-yw4l"></th>
            }
            else
            {
                <th class="tg-yw4l">@col</th>}
        }
    </tr>

    @foreach (var hour in hourItems)
    {
        foreach (var minute in minuteItems)
        {
            <tr>
                @foreach (var col in columns)
                {
                    if (col == "HOUR")
                    {
                        //First column, print the time
                        <td class="tg-yw41">@hour:@minute</td>
                    }
                    else
                    {

                        if (isConstrained(col, hour, minute))
                        {
                            <td class="tg-yw41 blocked"></td>
                        }
                        else
                        {
                            <td class="tg-yw41"></td>
                        }


                    }
                }
            </tr>
        }
    }
</table>
<table id="list" class="tg">
    <tr>
        <th class="tg-yw4l">Week Day</th>
        <th class="tg-yw4l">Start Time</th>
        <th class="tg-yw4l">End Time</th>
        <th class="tg-yw4l"></th>
    </tr>

    @foreach (QFGreenBean.Models.StudentConstraint constraint in Model)
    {
        @Html.Partial("~/Views/Constraint/_DeleteConstraint.cshtml", constraint);
    }

    @Html.Partial("~/Views/Constraint/_AddConstraint.cshtml", new QFGreenBean.Models.StudentConstraint());
</table>

QFGreenBean/QFGreenBean/Views/Constraint/_AddConstraint.cshtml
@model QFGreenBean.Models.StudentConstraint

@{
    List<SelectListItem> hourItems = new List<SelectListItem>();
    for (int i = 8; i <= 22; i++)
    {
        hourItems.Add(new SelectListItem
        {
            Text = Convert.ToString(i),
            Value = Convert.ToString(i)
        });
    }

    List<SelectListItem> minuteItems = new List<SelectListItem>();
    minuteItems.Add(new SelectListItem
    {
        Text = "00",
        Value = "00"
    });
    minuteItems.Add(new SelectListItem
    {
        Text = "15",
        Value = "15"
    });
    minuteItems.Add(new SelectListItem
    {
        Text = "30",
        Value = "30"
    });
    minuteItems.Add(new SelectListItem
    {
        Text = "45",
        Value = "45"
    });

    List<SelectListItem> weekdayItems = new List<SelectListItem>();
    weekdayItems.Add(new SelectListItem
    {
        Text = "Monday",
        Value = "monday"
    });
    weekdayItems.Add(new SelectListItem
    {
        Text = "Tuesday",
        Value = "tuesday"
    });
    weekdayItems.Add(new SelectListItem
    {
        Text = "Wednesday",
        Value = "wednesday"
    });
    weekdayItems.Add(new SelectListItem
    {
        Text = "Thursday",
        Value = "thursday"
    });
    weekdayItems.Add(new SelectListItem
    {
        Text = "Friday",
        Value = "friday"
    });

}
@using (Html.BeginForm("SubmitConstraint", "Constraint"))
{
    @Html.AntiForgeryToken()
    <tr>
        <td class="tg-yw4l">@Html.DropDownListFor(m => m.Day, new SelectList(weekdayItems, "Value", "Text"))</td>
        <td class="tg-yw4l">@Html.DropDownListFor(m => m.StartHour, new SelectList(hourItems, "Value", "Text")):@Html.DropDownListFor(m => m.StartMinute, new SelectList(minuteItems, "Value", "Text"))</td>
        <td class="tg-yw4l">@Html.DropDownListFor(m => m.EndHour, new SelectList(hourItems, "Value", "Text")):@Html.DropDownListFor(m => m.EndMinute, new SelectList(minuteItems, "Value", "Text"))</td>
        <td class="tg-yw4l"><button name="Submit" value="SubmitConstraint">Add</button></td>
    </tr>
    <h3>@Html.ValidationMessageFor(m => m.EndHour)</h3>
}

QFGreenBean/QFGreenBean/Views/Constraint/_DeleteConstraint.cshtml
@model QFGreenBean.Models.StudentConstraint

@functions {
    static string Capitalize(string s)
    {
        if (string.IsNullOrEmpty(s))
        {
            return string.Empty;
        }
        return char.ToUpper(s[0]) + s.Substring(1);
    }
}

@using (Html.BeginForm("DeleteConstraint", "Constraint"))
{
    @Html.AntiForgeryToken();
    @Html.HiddenFor(m => m.StudentConstraintId);
    <tr>
        <td class="tg-yw4l">@Capitalize(Model.Day)</td>
        <td class="tg-yw4l">@Model.StartHour : @Model.StartMinute</td>
        <td class="tg-yw4l">@Model.EndHour : @Model.EndMinute</td>
        <td class="tg-yw4l"><button name="Submit" value="DeleteConstraint">Delete</button></td>
    </tr>
}